auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h

limits_config:
  allow_structured_metadata: false
  ingestion_rate_mb: 4
  ingestion_burst_size_mb: 6

# ruler:
#   alertmanager_url: http://alertmanager:9093
#   storage:
#     type: local
#     local:
#       directory: /etc/loki
#   rule_path: /etc/loki/rules
#   alertmanager_refresh_interval: 1m
#   enable_api: true
#   enable_alertmanager_v2: true
#   external_url: http://localhost:3100

# By default, Loki will send anonymous, but uniquely-identifiable usage and configuration
# analytics to Grafana Labs. These statistics are sent to https://stats.grafana.org/
#
# Statistics help Grafana Labs understand how Loki is used. This helps drive
# product decisions that allow us to build a better Loki for our users.
#
# To disable analytics, uncomment the following line:
#analytics:
#  reporting_enabled: false
